#!/usr/bin/env python

import sys
from PySide.QtCore import QUrl
from PySide.QtGui import QApplication
from PySide.QtWebKit import QWebView, QWebPage

url = "http://dev.sencha.com/deploy/dev/examples/grouptabs/grouptabs.html"

app = QApplication(sys.argv)

web = QWebView()
web.setWindowTitle("Desktop application example")
web.resize(800, 600)
web.load(QUrl(url))
web.show()

sys.exit(app.exec_())
