#!/usr/bin/env python

import sys
from PySide.QtCore import QUrl
from PySide.QtGui import QApplication
from PySide.QtWebKit import QWebView, QWebPage

url = "http://dev.sencha.com/deploy/touch/examples/kitchensink/"

class MyWebPage(QWebPage):

    def userAgentForUrl(self, url):
        # Pretend that we are running Nexus One:
        return "Mozilla/5.0 (Linux; U; Android 2.2; en-us; Nexus One Build/FRF91) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"

app = QApplication(sys.argv)

web = QWebView()
web.setWindowTitle("Kitchen Sink")
web.setPage(MyWebPage())
# Make it look like Nexus
scale = 0.5
web.resize(480 * scale, 800 * scale)
web.load(QUrl(url))
web.show()

sys.exit(app.exec_())
